### ISSUE TITLE
Compiling on Node v4+ #UpstreamIssue

### ISSUE THREAD

**Issue by jnovack** [fehmer/adafruit-i2c-lcd#11]
There is an upstream issue with [`node-i2c`](https://github.com/kelly/node-i2c/) when compiling on gcc v4.8+ and node v4+.  This is NOT an issue with this library (`adafruit-i2c-lcd`), it is here merely for documentation.

The issue is fully documented in [`node-i2c`'s issue tracker](https://github.com/kelly/node-i2c/issues/69).  ~~A pull request to `node-i2c` has been created, and should be bumped mercilessly until fixed.~~ (*Edit: upstream maintainer does not want any fixes until he completes the full re-write that hasn't been started. So this issue might be here for a while.*)

*Issue*
Node changed the way it allocates buffers in v4.0.0 and causes breaking changes.

*Workaround*
Until this gets fixed upstream (HA!), you must trick npm into believing you have the fixed version of `node-i2c` before you install this package (`adafruit-i2c-lcd`).

* `npm install -g https://github.com/jnovack/node-i2c/archive/master.zip`

This will install my fork of `node-i2c` globally (where the fix is applied) so that `adafruit-i2c-led` will just link to the already download version, rather than downloading its own.

*References*

* [Diff of changes to `node-i2c`](https://github.com/kelly/node-i2c/compare/master...jnovack:master)

**Comment by fehmer** [comment]
Hi @jnovack 

thank you very much for your input. Since the upstram issue is not very likely to get fixed i decided to switch to [i2c-bus](https://www.npmjs.com/package/i2c-bus). This should solve the issues with newer node versions. 

I just released 1.0.0 to npmjs. Can you try this version and tell me if this issue is solved by the new version? Thanks
christian
